# Generated by Django 4.1.7 on 2023-02-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="produits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libellé", models.CharField(max_length=100)),
                ("description", models.TextField(default="Non défenie")),
                (
                    "prix",
                    models.DecimalField(decimal_places=3, default=10, max_digits=10),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("em", "Emballé"),
                            ("fr", "Frais"),
                            ("cs", "Conserve"),
                        ],
                        default="em",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
