# Generated by Django 4.1.7 on 2023-03-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magasin", "0002_produit_delete_produits"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="Img",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
