# Generated by Django 4.1.7 on 2023-03-07 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magasin", "0005_categorie"),
    ]

    operations = [
        migrations.RemoveField(model_name="categorie", name="catégorie",),
    ]
