# Generated by Django 4.1.7 on 2023-03-07 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("magasin", "0006_remove_categorie_catégorie"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorie",
            name="catégorie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="magasin.categorie",
            ),
        ),
    ]
