# Generated by Django 4.1.7 on 2023-03-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magasin", "0009_alter_categorie_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="name",
            field=models.CharField(
                choices=[
                    ("Al", "Alimentaire"),
                    ("Mb", "Meuble"),
                    ("Sn", "Sanitaire"),
                    ("Vs", "Vaisselle"),
                    ("Vt", "Vêtement"),
                    ("Jx", "Jouets"),
                    ("Lg", "Linge de Maison"),
                    ("Bj", "Bijoux"),
                    ("Dc", "Décor"),
                ],
                default="Al",
                max_length=50,
            ),
        ),
    ]
