# Generated by Django 4.1.7 on 2023-03-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magasin", "0013_produitnc"),
    ]

    operations = [
        migrations.RenameField(model_name="produit", old_name="Img", new_name="img",),
    ]
