# Generated by Django 4.1.7 on 2023-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magasin", "0022_alter_produit_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="fournisseur",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
