# Generated by Django 4.1.7 on 2023-03-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magasin", "0023_fournisseur_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fournisseur", old_name="img", new_name="logo",
        ),
    ]
